# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\trecommend\"(\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"W\n\x16RecommendationResponse\x12\x10\n\x08video_id\x18\x01 \x01(\x05\x12\x12\n\nvideo_name\x18\x02 \x01(\t\x12\x17\n\x0f\x63over_image_url\x18\x03 \x01(\t\"X\n\x1aRecommendationResponseList\x12:\n\x0frecommendations\x18\x01 \x03(\x0b\x32!.recommend.RecommendationResponse2r\n\x10RecommendService\x12^\n\x13ListRecommendations\x12 .recommend.RecommendationRequest\x1a%.recommend.RecommendationResponseListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=28
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=68
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=70
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=157
  _globals['_RECOMMENDATIONRESPONSELIST']._serialized_start=159
  _globals['_RECOMMENDATIONRESPONSELIST']._serialized_end=247
  _globals['_RECOMMENDSERVICE']._serialized_start=249
  _globals['_RECOMMENDSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
