// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: scrapeService.proto

package scrapeService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoParms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Release string `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
	Area    string `protobuf:"bytes,3,opt,name=area,proto3" json:"area,omitempty"`
	Episode string `protobuf:"bytes,4,opt,name=episode,proto3" json:"episode,omitempty"`
	Replace string `protobuf:"bytes,5,opt,name=replace,proto3" json:"replace,omitempty"`
}

func (x *VideoParms) Reset() {
	*x = VideoParms{}
	mi := &file_scrapeService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoParms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoParms) ProtoMessage() {}

func (x *VideoParms) ProtoReflect() protoreflect.Message {
	mi := &file_scrapeService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoParms.ProtoReflect.Descriptor instead.
func (*VideoParms) Descriptor() ([]byte, []int) {
	return file_scrapeService_proto_rawDescGZIP(), []int{0}
}

func (x *VideoParms) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VideoParms) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *VideoParms) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *VideoParms) GetEpisode() string {
	if x != nil {
		return x.Episode
	}
	return ""
}

func (x *VideoParms) GetReplace() string {
	if x != nil {
		return x.Replace
	}
	return ""
}

type VideoMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *VideoMsg) Reset() {
	*x = VideoMsg{}
	mi := &file_scrapeService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMsg) ProtoMessage() {}

func (x *VideoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_scrapeService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMsg.ProtoReflect.Descriptor instead.
func (*VideoMsg) Descriptor() ([]byte, []int) {
	return file_scrapeService_proto_rawDescGZIP(), []int{1}
}

func (x *VideoMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_scrapeService_proto protoreflect.FileDescriptor

var file_scrapeService_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x22, 0x82, 0x01,
	0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x61, 0x72, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72,
	0x65, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x32, 0x41, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x38, 0x0a, 0x0e, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x2e, 0x73, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x61, 0x72, 0x6d, 0x73, 0x1a,
	0x10, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x73,
	0x67, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scrapeService_proto_rawDescOnce sync.Once
	file_scrapeService_proto_rawDescData = file_scrapeService_proto_rawDesc
)

func file_scrapeService_proto_rawDescGZIP() []byte {
	file_scrapeService_proto_rawDescOnce.Do(func() {
		file_scrapeService_proto_rawDescData = protoimpl.X.CompressGZIP(file_scrapeService_proto_rawDescData)
	})
	return file_scrapeService_proto_rawDescData
}

var file_scrapeService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scrapeService_proto_goTypes = []any{
	(*VideoParms)(nil), // 0: scrape.videoParms
	(*VideoMsg)(nil),   // 1: scrape.videoMsg
}
var file_scrapeService_proto_depIdxs = []int32{
	0, // 0: scrape.Video.ScrapeVideoUrl:input_type -> scrape.videoParms
	1, // 1: scrape.Video.ScrapeVideoUrl:output_type -> scrape.videoMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scrapeService_proto_init() }
func file_scrapeService_proto_init() {
	if File_scrapeService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scrapeService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scrapeService_proto_goTypes,
		DependencyIndexes: file_scrapeService_proto_depIdxs,
		MessageInfos:      file_scrapeService_proto_msgTypes,
	}.Build()
	File_scrapeService_proto = out.File
	file_scrapeService_proto_rawDesc = nil
	file_scrapeService_proto_goTypes = nil
	file_scrapeService_proto_depIdxs = nil
}
